[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "12.16.2"
  NODE_ENV = "production"

[dev]
  command = "npm run start"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-nextjs"
